name: "check my website is working"

on: 
  push:
  schedule:
    - cron: '05 * * * *'

env:
  my_env_var: ${{ bash ./check_website.sh }}

jobs:
  my-job:
    name: my job
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Check Website'
        run: echo "::set-env name=WEBSITE_WORKING::$(bash ./check_website.sh)"
      - name: 'Get Date'
        run: echo "::set-env name=REPORT_DATE::$(TZ=':Asia/Changsha' date '+%Y-%m-%d %T')"
      - name: 'Send Mail'
        uses: dawidd6/action-send-mail@master
        if: 200 == 200
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: MangoCool Website is Not Working (${{env.REPORT_DATE}})
          body: my mangocool website is not working.
          to: 58742094@qq.com
          from: GitHub Actions
          content_type: text/html
