name: "check my website is working"

on: 
  push:
  schedule:
    - cron: '05 * * * *'

jobs:
  my-job:
    name: my job
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Check Website'
        run: bash ./check_website.sh
      
