name: "check sszw website is working"

on: 
  push:
  schedule:
    - cron: '10 * * * *'


jobs:
  my-job:
    name: my job
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Check Website'
        run: echo "::set-env name=WEBSITE_WORKING::$(bash ./sszw_check_website.sh)"
      - name: 'Get Date'
        run: echo "::set-env name=REPORT_DATE::$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')"
      - name: 'Send Mail'
        if: env.WEBSITE_WORKING != 200
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: SSZW Website is Not Working (${{env.WEBSITE_WORKING}}) (${{env.REPORT_DATE}})
          body: my sszw website is not working.
          to: 58742094@qq.com
          from: GitHub Actions
          content_type: text/html
